config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    get '/' => 'homes#top'
    resources :users, only: [:show, :destroy]
    resources :post_comments, only: [:index, :destroy]
    resources :events, only: [:new, :create, :index, :destroy]
  end

  root to: 'homes#top'
  get "search" => "searches#search"
  devise_for :users
  get '/events', to: 'events#index'
  get 'events/:id', to: 'events#show'
  get 'event', to: 'events#index', defaults: { format: 'json' }
  resources :users, only: [:show, :edit, :index, :update, :destroy] do
    resources :roots, only: [:new, :show, :index, :edit, :create], shallow: true
    resources :activities, only: [:new, :create, :index, :destroy]
  end
  resources :posts do
    resources :post_comments, only: [:new, :create, :index, :destroy]
  end
  resources :groups do
    resources :permits, only: [:create, :destroy]
    resource :group_users, only: [:create, :destroy]
  end
  get "groups/:id/permits" => "groups#permits", as: :permits
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  validates :mileage, presence: true
  validates :hour, presence: true
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise authentication_keys: [:email]

  has_many :events, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :admin

  validates :title, presence: true
  validates :detail, presence: true
  validates :location, presence: true, length: { in: 1..100 }
  validates :start, presence: true
  validates :end, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :theme, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true

  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

app/models/root.rb
class Root < ApplicationRecord
  belongs_to :user

  geocoded_by :address
  after_validation :geocode

  def display_markers_for_favorite_course(favorite_course_id)
    roots = Root.where(favorite_course_id: favorite_course_id).select(:latitude, :longitude)
    markers = roots.map { |root| { lat: root.latitude, lng: root.longitude } }
    return markers
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :activities, dependent: :destroy
  has_many :roots, dependent: :destroy
  
  has_one_attached :profile_image

  validates :email, presence: true
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :course_introduction, presence: false, length: { maximum: 200 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.admin_id = current_admin.id
    if @event.save
      flash[:notice] = "Create event!"
      redirect_to admin_path
    else
      flash[:notice] = "Uncreate event"
      render 'admin/homes/top'
    end
  end

  def index
    @events = Event.all
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    flash[:notice] = "Delete event"
    redirect_to admin_path
  end

  private

  def event_params
  params.require(:event).permit(:title, :detail, :location, :start, :end)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    respond_to do |format|
      format.html
      format.json { render 'calendar' }
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
  params.require(:event).permit(:title, :detail, :location, :start, :end)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/permits_helper.rb
module PermitsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/events/_index.html.erb
<div class="col-md-5 mt-3">
  <h5 class="text-center mb-4 mt-5">-New event-</h5>
  <%= render 'admin/events/new', event: @event %>
</div>

<div class="offset-md-1"></div>

<div class="col-md-5 mt-3">
  <h5 class="text-center mb-4 mt-5">-All events-</h5>
  <div class="scrollable-container" style="height: 500px; overflow-y: scroll;">
    <table class="table table-hover table-responsive-sm">
      <% if @events.present? %>
      <% @events.reverse_each do |event| %>
      <tbody class="table-group-divider">
        <tr>
          <td>
            <p>・Title：<%= event.title %></p>
            <p>・Detail<%= event.detail %></p>
            <p>・Schedule<%= event.start %> ~ <%= event.end %><p>
            <p>・Location<%= event.location %></p>
            <%= link_to 'Delete', admin_event_path(event), method: :delete, data: {confirm: "Are you sure you want to delete?"} %>
          </td>
        </tr>
      </tbody>
      <% end %>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/events/_new.html.erb
<div class="error message mt-4 mb-4">
  <% if event.errors.any? %>
    <%= event.errors.count %>error occurred!
    <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<div class="from mt-5">
  <%= form_with model: event, url: admin_events_path, method: :post do |f| %>
  <%= f.label :Title %>
  <%= f.text_field :title, class: "form-control mb-3" %>
  <%= f.label :Detail %>
  <%= f.text_field :detail, class: "form-control mb-3" %>
  <%= f.label :Schedule %></br>
  <%= f.datetime_select :start, class: "form-control mb-3", options: { ampm: true } %><br>
  <%= f.datetime_select :end, class: "form-control mb-3", options: { ampm: true } %></br>
  <%= f.label :Location, class:"mt-3" %>
  <%= f.text_field :location, class: "form-control mb-3" %>
  <button class="btn btn-outline-success btn-block mt-5" type="submit">Create</button>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="container-floid m-5">
  <h3 class="text-center mb-5">-Event calendar-</h3>
  <div class="row justify-content-center">
    <div class="col-8">
        <%= javascript_pack_tag 'application' %>
        <div id="calendar"></div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container-floid m-5">
  <h3 class="text-center mb-5">-Event show-</h3>
  <div class="row justify-content-center">
    <div class="col-md-5">
      <h4>・Title：<%= @event.title %></h4>
      <h4>・Detail：<%= @event.detail %></h4>
      <h4>・Location：<%= @event.location %></h4>
      <h4>・Schedule　Start：<%= @event.start.strftime("%Y-%m-%d  %H:%M") %> ~</h4>
      <h4>　　　　　　    End：<%= @event.end.strftime("%Y-%m-%d  %H:%M") %></h4>
    </div>
  </div>
  <div class="row justify-content-center mt-4">
    <%= link_to 'Back', events_path, class:"btn btn-outline-success", style: "width: 30%;" %>
  </div>
</div>