config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    get '/' => 'homes#top'
    resources :users, only: [:show, :destroy]
    resources :post_comments, only: [:index, :destroy]
    resources :events, only: [:new, :create, :index, :destroy]
  end

  root to: 'homes#top'
  get "search" => "searches#search"
  devise_for :users
  get '/events', to: 'events#index'
  get 'events/:id', to: 'events#show'
  get 'event', to: 'events#index', defaults: { format: 'json' }
  resources :users, only: [:show, :edit, :index, :update, :destroy] do
    resources :roots, only: [:new, :show, :index, :edit, :create], shallow: true
    resources :activities, only: [:new, :create, :index, :destroy]
  end
  resources :posts do
    resources :post_comments, only: [:new, :create, :index, :destroy]
  end
  resources :groups do
    resources :permits, only: [:create, :destroy]
    resource :group_users, only: [:create, :destroy]
  end
  get "groups/:id/permits" => "groups#permits", as: :permits
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  validates :mileage, presence: true
  validates :hour, presence: true
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise authentication_keys: [:email]

  has_many :events, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :admin

  validates :title, presence: true
  validates :detail, presence: true
  validates :location, presence: true, length: { in: 1..100 }
  validates :start, presence: true
  validates :end, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :theme, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true

  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

app/models/root.rb
class Root < ApplicationRecord
  belongs_to :user

  geocoded_by :address
  after_validation :geocode

  def display_markers_for_favorite_course(favorite_course_id)
    roots = Root.where(favorite_course_id: favorite_course_id).select(:latitude, :longitude)
    markers = roots.map { |root| { lat: root.latitude, lng: root.longitude } }
    return markers
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :activities, dependent: :destroy
  has_many :roots, dependent: :destroy
  
  has_one_attached :profile_image

  validates :email, presence: true
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :course_introduction, presence: false, length: { maximum: 200 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :permits]

  def index
    @groups = Group.all
    if params[:id].present?
      set_group
    else
      @group = Group.new
    end
  end

  def show
    @group = Group.find(params[:id])
    @permits = @group.permits.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      redirect_to groups_path
    else
      @groups = Group.all
      render 'index'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_path
    else
      render 'edit'
    end
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    redirect_to groups_path
  end
  
  def permits
    @group = Group.find(params[:id])
    @permits = @group.permits.all
  end

  private

  def group_params
    params.require(:group).permit(:name, :theme)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to group_path(@group), alert: "Only the group owner can edit it."
    end
  end


end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/permits_helper.rb
module PermitsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_new.html.erb
<div class="container">
      <h5 class=" text-center mb-5 mt-3">New group</h5>

      <div class="error message mt-4 mb-4">
        <% if group.errors.any? %>
          <%= group.errors.count %>error occurred!
          <ul>
            <% group.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>

      <div class="from mt-4">
        <%= form_with model: group do |f| %>
          <h4>Name</h4>
          <%= f.text_field :name, class: "form-control mb-3", placeholder: "Group name" %>
          <h4>Theme</h4>
          <%= f.text_area :theme, class: "form-control mb-3", style: "height: 220px;", placeholder: "Group theme" %>
          <button class="btn btn-outline-success btn-block mt-3" type="submit">Create</button>
        <% end %>
      </div>

</div>

app/views/groups/_permits.html.erb
      <h6 class="text-center mb-4 mt-5">-Weiting member-</h6>
      <div class="scrollable-container" style="height: 200px; overflow-y: scroll;">
        <table class="table table-hover table-responsive-sm">
        <% if permits.present? %>
          <% permits.each do |permit| %>
            <tbody class="table-group-divider">
              <tr>
                <th scope="row">
                  <%= image_tag permit.user.get_profile_image(100,100), class: "rounded-circle", style: "width: 50px; height: 50px;" %>
                </th>
                <td style="text-align: right;">
                  
                  <%= link_to permit.user.name, user_path(permit.user.id), style:"color: #28a745;" %>さん&emsp;&emsp;
                  <%= link_to '加入許可', group_group_users_path(@group, permit_id: permit.id), method: :post, class:"btn btn-outline-success" %>
                
                </td>
              </tr>
            </tbody>
          <% end %>
        <% else %>
          <p class="text-center">No member</p>
        <% end %>
        </table>
      </div>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row justify-content-center mt-4">
    <div class="col-5 mt-4">
      <h3 class=" text-center">-Group edit-</h3>

      <div class="error message mt-4 mb-4">
        <% if @group.errors.any? %>
          <%= @group.errors.count %>error occurred.
          <ul>
            <% @group.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %> 
          </ul>
        <% end %>
      </div>

      <div class="from mb-4">
        <%= form_with model: @group do |f| %>
          <label for="inputNeme">Name</label>
          <%= f.text_field :name, class: "form-control mb-3", autofocus: true, id:"inputName" %>
          <label for="inputTheme">Theme</label>
          <%= f.text_area :theme, class: "form-control mb-3", style: "height: 220px;", autofocus: true, id:"inputTheme" %>
          <% if @group.owner_id == current_user.id %>
            <button class="btn btn-outline-success btn-block mt-4 mb-3" type="submit">Updata</button>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container-floid m-5">
  <h3 class="text-center mb-5">-Group Top-</h3>

    <div class="row">

      <div class="col-md-4">
        <%= render 'new', group: @group %>
      </div>
      <div class="offset-md-1"></div>

      <div class="col-md-7">
        <h5 class="text-center mb-5 mt-3">Group index</h5>
        <div class="scrollable-container" style="height: 500px; overflow-y: scroll;">
        <table class="table table-hover table-responsive-sm mt-3">
        <% if @groups.present? %>
          <% @groups.reverse_each do |group| %>
            <tbody class="table-group-divider">
            <tr>
              <td>
                <p>Name：<%= link_to group_path(group.id), style:"color: #28a745;" do %>
                  <%= group.name %>
                <% end %>
                <p class="wrap-text" style="word-break: break-all;">Theme：<%= group.theme.truncate(50) %></p>
                <div class="row">
                  <div class="col">
                    <i class="fa-solid fa-people-group"></i>
                    <%= group.group_users.count %>
                  </div>
                </div>
              </td>
            <tr>
            </tbody>
          <% end %>
        <% else %>
          <p>No group</p>
        <% end %>
        </table>
        </div>
      </div>
    </div>
</div>

app/views/groups/show.html.erb
<div class="container-floid m-5">
  <h3 class="text-center mb-4 mt-5">-Group show-</h3>
  <div class="row justify-content-center mt-3">
    <h1 class="display-4 mt-5"><%= @group.name %></h1>
  </div>
  <div class="row justify-content-center mt-5">
    <div class="col-10">
      <%= simple_format(@group.theme, sanitize: true, class:"wrap-text mt-2 text-left",style:"word-break: break-all;" ) %>
    </div>
  </div>

  <div class="row justify-content-center mt-3">
    <% if @group.owner_id == current_user.id %>
      <%= link_to 'Edit', edit_group_path(@group), class: 'nav-link text-success' %>
      <%= link_to 'Delete', group_path(@group), class: 'nav-link text-success', method: :delete, data: {confirm: "Are you sure you want to Delete?"} %>
    <% else %>
      <% if @group.group_users.exists?(user_id: current_user.id) %>
        <%= link_to 'Leave this group', group_group_users_path(@group), method: :delete, data: {confirm: "Are you sure you want to without?"} %>
      <% elsif @group.permits.exists?(user_id: current_user.id)  %>
        <%= link_to 'Request cancel', group_permit_path(@group), style:"color: #28a745;", method: :delete %>
      <% else %>
        <%= link_to 'Join request', group_permits_path(@group), style:"color: #28a745;", method: :post %>
      <% end %>
    <% end %>
  </div>

  <% if @group.owner_id == current_user.id %>
  <div class="row justify-content-center">
    <div class="col-md-5 mt-3">
    <h6 class="text-center mb-4 mt-5">-Member-</h6>
    <div class="scrollable-container" style="height: 200px; overflow-y: scroll;">
      <table class="table table-hover table-responsive-sm">
      <% if @group.group_users.present? %>
        <% @group.users.each do |member| %>
          <tbody class="table-group-divider border-top-color-black">
            <tr>
              <th scope="row">
                <%= image_tag member.get_profile_image(100,100), class: "rounded-circle", style: "width: 50px; height: 50px;" %>
              </th>
              <td>
                <%= member.name %>
              </td>
            </tr>
          </tbody>
        <% end %>
      <% else %>
        <p class="text-center">No member</p>
      <% end %>
      </table>
      </div>
    </div>

    <div class="col-md-5 mt-3">
      <%= render 'permits', permits: @permits %>
    </div>
  </div>

  <% else %>
  
  <div class="row justify-content-center">
    <div class="col-md-5 mt-3">
    <div class="scrollable-container" style="height: 200px; overflow-y: scroll;">
    <h6 class="text-center mb-4 mt-5">-Member-</h6>
      <table class="table table-hover table-responsive-sm">
      <% if @group.group_users.present? %>
        <% @group.users.each do |member| %>
          <tbody class="table-group-divider border-top-color-black">
            <tr>
              <th scope="row">
                <%= image_tag member.get_profile_image(100,100), class: "rounded-circle", style: "width: 50px; height: 50px;" %>
              </th>
              <td>
                <%= link_to user_path, style:"color: #28a745;" do %>
                  <%= member.name %>
                <% end %>さん
              </td>
            </tr>
          </tbody>
        <% end %>
      <% else %>
        <p class="text-center">No member</p>
      <% end %>
      </table>
      </div>
    </div>
  <% end %>

</div>