config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    get '/' => 'homes#top'
    resources :users, only: [:show, :destroy]
    resources :post_comments, only: [:index, :destroy]
    resources :events, only: [:new, :create, :index, :destroy]
  end

  root to: 'homes#top'
  get "search" => "searches#search"
  devise_for :users
  get '/events', to: 'events#index'
  get 'events/:id', to: 'events#show'
  get 'event', to: 'events#index', defaults: { format: 'json' }
  resources :users, only: [:show, :edit, :index, :update, :destroy] do
    resources :roots, only: [:new, :show, :index, :edit, :create], shallow: true
    resources :activities, only: [:new, :create, :index, :destroy]
  end
  resources :posts do
    resources :post_comments, only: [:new, :create, :index, :destroy]
  end
  resources :groups do
    resources :permits, only: [:create, :destroy]
    resource :group_users, only: [:create, :destroy]
  end
  get "groups/:id/permits" => "groups#permits", as: :permits
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  validates :mileage, presence: true
  validates :hour, presence: true
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise authentication_keys: [:email]

  has_many :events, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :admin

  validates :title, presence: true
  validates :detail, presence: true
  validates :location, presence: true, length: { in: 1..100 }
  validates :start, presence: true
  validates :end, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :theme, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true

  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

app/models/root.rb
class Root < ApplicationRecord
  belongs_to :user

  geocoded_by :address
  after_validation :geocode

  def display_markers_for_favorite_course(favorite_course_id)
    roots = Root.where(favorite_course_id: favorite_course_id).select(:latitude, :longitude)
    markers = roots.map { |root| { lat: root.latitude, lng: root.longitude } }
    return markers
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :activities, dependent: :destroy
  has_many :roots, dependent: :destroy
  
  has_one_attached :profile_image

  validates :email, presence: true
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :course_introduction, presence: false, length: { maximum: 200 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    @search = params[:search]
    @word = params[:word]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @posts = Post.looks(params[:search], params[:word])
    end
    render 'search_result'
  end
  
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/permits_helper.rb
module PermitsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/searches/_search.html.erb
<div class="container-fluid d-flex justify-content-end">
  <% if user_signed_in? %>
    <div class="search_form ">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <div class="row align-items-center">
      <div class="col-auto pr-0"><%= f.text_field :word %></div>
      <div class="col-auto pr-0"><%= f.select :range, options_for_select([['User'], ['Post']]) %></div>
      <div class="col-auto pr-0"><%= f.select :search, options_for_select([["perfect match","perfect_match"], ["forward match","forward_match"],  ["backward match","backward_match"], ["partial match","partial_match"]]) %></div>
      <div class="col-auto pr-0"><%= f.submit "search", class: "btn btn-outline-dark text-success" %></div>
      </div>
    <% end %>
  </div>
<% end %>
</div>

app/views/searches/search_result.html.erb
<div class="container mt-5">
  <h3 class="text-center">-Results index-</h3>
  <div class="row justify-content-center mt-4">
    <% if @range.present? %>
    <div class="col-8 mt-3">
      <table class="table table-hover table-responsive-sm">
        <% if @range == "User" %>
          <tbody class="table-group-divider">
          <% @users.reverse_each do |user| %>
            <tr>
              <th scope="row"><%= image_tag user.get_profile_image(100,100), class: "rounded-circle", style: "width: 80px; height: 80px;" %></th>
              <td><%= user.name %></td>
              <td><%= link_to "show page", user_path(user.id), class: 'btn btn-outline-success' %>&emsp;&emsp;
                <% if user == current_user %>
                  <%= link_to "Edit", edit_user_path(user), class: 'btn btn-outline-success' %>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        <% else %>
          <tbody class="table-group-divider">
          <% @posts.reverse_each do |post| %>
            <tr>
              <th scope="row"><%= image_tag post.user.get_profile_image(100,100), class: "rounded-circle", style: "width: 80px; height: 80px;" %></th>
              <td>
                <%= link_to post_path(post.id) do %>
                  <%= post.title %>
                <% end %>
                <p class="wrap-text" style="word-break: break-all;"><%= post.body.truncate(50) %></p>
                <div class="row">
                  <div class="col-4"><%= post.user.name %>さん</div>
                  <div class="col-3">
                    <i class="fa-regular fa-comment"></i>&emsp;
                    <%= "#{post.post_comments.count}" %></div>
                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
        <% end %>
      </table>
      </div>
    <% else %>
      <p>No information matching</p>
    <% end %>
  </div>
</div>