config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    get '/' => 'homes#top'
    resources :users, only: [:show, :destroy]
    resources :post_comments, only: [:index, :destroy]
    resources :events, only: [:new, :create, :index, :destroy]
  end

  root to: 'homes#top'
  get "search" => "searches#search"
  devise_for :users
  get '/events', to: 'events#index'
  get 'events/:id', to: 'events#show'
  get 'event', to: 'events#index', defaults: { format: 'json' }
  resources :users, only: [:show, :edit, :index, :update, :destroy] do
    resources :roots, only: [:new, :show, :index, :edit, :create], shallow: true
    resources :activities, only: [:new, :create, :index, :destroy]
  end
  resources :posts do
    resources :post_comments, only: [:new, :create, :index, :destroy]
  end
  resources :groups do
    resources :permits, only: [:create, :destroy]
    resource :group_users, only: [:create, :destroy]
  end
  get "groups/:id/permits" => "groups#permits", as: :permits
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  validates :mileage, presence: true
  validates :hour, presence: true
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise authentication_keys: [:email]

  has_many :events, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :admin

  validates :title, presence: true
  validates :detail, presence: true
  validates :location, presence: true, length: { in: 1..100 }
  validates :start, presence: true
  validates :end, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :theme, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true

  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

app/models/root.rb
class Root < ApplicationRecord
  belongs_to :user

  geocoded_by :address
  after_validation :geocode

  def display_markers_for_favorite_course(favorite_course_id)
    roots = Root.where(favorite_course_id: favorite_course_id).select(:latitude, :longitude)
    markers = roots.map { |root| { lat: root.latitude, lng: root.longitude } }
    return markers
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :activities, dependent: :destroy
  has_many :roots, dependent: :destroy
  
  has_one_attached :profile_image

  validates :email, presence: true
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :course_introduction, presence: false, length: { maximum: 200 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "Delete user"
    redirect_to admin_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to new_user_registration_path
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :course_introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/permits_helper.rb
module PermitsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/show.html.erb
<div class="container-floid m-5 bg-white">
  <div class="row justify-content-center mb-3 mt-4">
    <%= image_tag @user.get_profile_image(100,100), class: "rounded-circle", style: "width: 130px; height: 130px;" %>
  </div>
  <div class="row justify-content-center mt-4">
    <h3><%= @user.name %></h3>
  </div>
  <div class="row justify-content-center mt-3 pb-3">
    <%= link_to "Delete", admin_user_path(@user), class:"btn btn-outline-dark", role: 'button', method: :delete, data: { confirm: 'Are you sure you want to delete?' } %>
  </div>

  <h3 class="text-center pt-5">- Post index -</h3>
  <div class="row justify-content-center">
    <div class="col-8 mt-3">
      <table class="table table-hover table-responsive-sm">
        <% @posts.reverse_each do |post| %>
        <tbody class="table-group-divider">
          <tr>
            <td>
              <p>Title：<%= post.title %></p>
              <p class="wrap-text" style="word-break: break-all;">
                Body：<%= post.body.truncate(50) %></p>
              <div class="row">
                <div class="col-4"><%= post.user.name %>さん</div>
                <div class="col-3">
                  <i class="fa-regular fa-comment"></i>&emsp;
                  <%= "#{post.post_comments.count}" %>comments</div>
              </div>
            </td>
          </tr>
        </tbody>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row justify-content-center mt-4">
    <div class="col-5 mt-4">
      <h3 class=" text-center">-Profile edit-</h3>

      <div class="error message mt-4 mb-4">
        <% if @user.errors.any? %>
          <%= @user.errors.count %>error occurred.
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>

      <div class="from mb-4">
        <%= form_with model: @user do |f| %>
          <label for="InputName">Name</label>
          <%= f.text_field :name, class: "form-control mb-3", autofocus: true, id:"inputName", placeholder:"Name" %>
          <label for="InputCourseintroduction">Course Introduction</label>
          <%= f.text_area :course_introduction, class: "form-control mb-3", style: "height: 220px;", autofocus: true, id:"inputCourseintroduction", placeholder:"Introduction" %>
          <label for="InputImage">Profile Image</label><br>
          <%= f.file_field :profile_image, accept: "image/*" %>
          <% if @user == current_user %>
            <button class="btn btn-outline-success btn-block mt-4 mb-3" type="submit">Save</button>
            <%= link_to "Withdrawal", user_path(@user), style:"color: #28a745;", method: :delete, data: {confirm: "Are you sure you want to Withdrawal"} %>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5 bg-white">
  <div class="row justify-content-center mb-3 mt-4">
    <%= image_tag @user.get_profile_image(100,100), class: "rounded-circle", style: "width: 130px; height: 130px;" %>
  </div>
  <div class="row justify-content-center mt-4">
    <h3><%= @user.name %></h3>
  </div>
  <div class="row justify-content-center mt-3">
    <% if @user == current_user %>
      <%= link_to "Plofile edit",edit_user_path(@user.id), class:"btn btn-outline-dark", role: 'button' %>
    <% end %>
  </div>
  <div class="row justify-content-center text-center mt-5 mb-4">
    <% if @user == current_user %>
    <div class="col-3">
      <%= link_to "calendar", events_path, data: {"turbolinks" => false}, class: 'btn btn-outline-success btn-lg', style:'height: 110px; width: 110px; line-height: 90px;'%></div>
    <div class="col-3">
      <%= link_to "Group", groups_path, class: 'btn btn-outline-success btn-lg', style:'height: 110px; width: 110px; line-height: 90px;' %></div>
    <div class="col-3">
      <%= link_to "Activity", user_activities_path(current_user), class: 'btn btn-outline-success btn-lg', style:'height: 110px; width: 110px; line-height: 90px;'%></div>
    <div class="col-3">
      <%= link_to 'Course', user_roots_path(current_user), class: 'btn btn-outline-success btn-lg', style:'height: 110px; width: 110px; line-height: 90px;' %></div>
    <% end %>
  </div>
  
  <h2 class="row justify-content-center pb-5 pt-5">-Post index-</h2>
  <div class="row justify-content-center text-center mb-3">
    <div class="post mt-2">
      <% if @posts.present? %>
        <% @posts.reverse_each do |post| %>
          <div class="title text-center mb-4">
            <%= link_to post_path(post.id), style:"color: #28a745;" do %>
              <%= post.title %>
            <% end %></p>
            <p><%= post.user.name %></p>
            <%= "#{post.post_comments.count} comment"%>
          </div>
        <% end %>
      <% else %>
        <P>No post</p>
      <% end %>
     </div>
  </div>
  
</div>